import type { Skill, SkillCategory } from "./skills.types";

export const skillCategories: SkillCategory[] = [
  {
    id: "backend",
    label: "Backend",
    code: "BE",
    description: "APIs, business logic, integrations, and server-side systems.",
  },
  {
    id: "frontend",
    label: "Frontend",
    code: "FE",
    description: "Responsive interfaces and component-driven web applications.",
  },
  {
    id: "data-caching",
    label: "Data & Caching",
    code: "DC",
    description: "Persistent storage, query design, and fast temporary data access.",
  },
  {
    id: "infrastructure",
    label: "Infrastructure",
    code: "IN",
    description: "Reproducible environments and application delivery workflows.",
  },
  {
    id: "workflow",
    label: "Workflow",
    code: "WF",
    description: "Tools used to design, collaborate, and accelerate delivery.",
  },
];

export const skills: Skill[] = [
  {
    id: "gin",
    code: "BE-01",
    name: "Gin",
    category: "backend",
    role: "HTTP Web Framework",
    language: "Go",
    summary: "Building typed services with explicit boundaries and predictable performance.",
    useCases: ["REST APIs", "Clean architecture", "Concurrent services"],
    projects: ["E-Commerce Platform"],
  },
  {
    id: "laravel",
    code: "BE-02",
    name: "Laravel",
    category: "backend",
    role: "Web Framework",
    language: "PHP",
    summary: "Developing full-stack applications and maintainable REST API backends.",
    useCases: ["Authentication", "Business workflows", "API development"],
    projects: ["Nutrihealth", "Website-IOT"],
  },
  {
    id: "fastapi",
    code: "BE-03",
    name: "FastAPI",
    category: "backend",
    role: "API Framework",
    language: "Python",
    summary: "Creating Python APIs for automation, scraping, and AI integrations.",
    useCases: ["Async APIs", "AI integration", "Data pipelines"],
    projects: ["Web Scraping Platform"],
  },
  {
    id: "nextjs",
    code: "FE-01",
    name: "Next.js",
    category: "frontend",
    role: "React Framework",
    language: "TypeScript",
    summary: "Shipping optimized interfaces with routing, rendering, and server capabilities.",
    useCases: ["App Router", "SEO", "Full-stack UI"],
    projects: ["E-Commerce Platform", "Chess Web App"],
  },
  {
    id: "react",
    code: "FE-02",
    name: "React",
    category: "frontend",
    role: "UI Library",
    language: "TypeScript",
    summary: "Building reusable interface systems with clear component responsibilities.",
    useCases: ["Component systems", "Interactive UI", "State management"],
    projects: ["Portfolio", "Chess Web App"],
  },
  {
    id: "postgresql",
    code: "DC-01",
    name: "PostgreSQL",
    category: "data-caching",
    role: "Relational Database",
    summary: "Modeling transactional data with relational constraints and queryable structure.",
    useCases: ["Relational modeling", "Transactions", "Complex queries"],
    projects: ["E-Commerce Platform"],
  },
  {
    id: "mysql",
    code: "DC-02",
    name: "MySQL",
    category: "data-caching",
    role: "Relational Database",
    summary: "Designing dependable data storage for content and business applications.",
    useCases: ["Schema design", "CRUD systems", "Data reporting"],
    projects: ["Nutrihealth", "Website-IOT"],
  },
  {
    id: "redis",
    code: "DC-03",
    name: "Redis",
    category: "data-caching",
    role: "Caching & In-Memory Store",
    summary: "Reducing repeated work with fast temporary storage around backend workflows.",
    useCases: ["Response caching", "Session storage", "Rate limiting", "Temporary data"],
    projects: ["E-Commerce Platform"],
  },
  {
    id: "docker",
    code: "IN-01",
    name: "Docker",
    category: "infrastructure",
    role: "Container Platform",
    summary: "Keeping development and deployment environments reproducible across services.",
    useCases: ["Service containers", "Local environments", "Deployment packaging"],
    projects: ["E-Commerce Platform"],
  },
  {
    id: "figma",
    code: "WF-01",
    name: "Figma",
    category: "workflow",
    role: "Interface Design",
    summary: "Planning user flows and interface structure before implementation begins.",
    useCases: ["Wireframes", "Prototypes", "Design handoff"],
    projects: ["Portfolio", "Product prototypes"],
  },
  {
    id: "copilot",
    code: "WF-02",
    name: "GitHub Copilot",
    category: "workflow",
    role: "Development Assistant",
    summary: "Accelerating repetitive implementation while retaining manual review and control.",
    useCases: ["Code suggestions", "Boilerplate", "Implementation support"],
    projects: ["Daily development workflow"],
  },
];
